Description: CloudFormation Template to create an EC2 Instance with an Elastic IP, Security Group, EBS volume, and a web server setup. Outputs Public and Private IP addresses.

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-5b41123e'  # Replace with the appropriate AMI ID for your region
      SecurityGroups:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Welcome to your Web Server!</h1>" > /var/www/html/index.html
      Tags:
        - Key: Nisargi
          Value: MyEC2Instance

  MyElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      InstanceId: !Ref MyEC2Instance

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'

  MyEBSVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      AvailabilityZone: !GetAtt MyEC2Instance.AvailabilityZone
      Size: 10  # Size of the EBS volume in GB
      VolumeType: gp2
    DeletionPolicy: Retain

  MyVolumeAttachment:
    Type: 'AWS::EC2::VolumeAttachment'
    Properties:
      InstanceId: !Ref MyEC2Instance
      VolumeId: !Ref MyEBSVolume
      Device: '/dev/sdh'

Outputs:
  InstancePublicIP:
    Description: The Public IP address (Elastic IP) of the EC2 instance
    Value: !Ref MyElasticIP

  InstancePrivateIP:
    Description: The Private IP address of the EC2 instance
    Value: !GetAtt 
      - MyEC2Instance
      - PrivateIp

